# -*- coding: utf-8 -*-
"""Python-project( CONTDOWN-TIMER).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10gap3nmmgC_SjbfTNhXoOD2j7EQQOWHQ
"""

import time

def contdown(t):
    while t:
        mins, secs = divmod(t, 60)
        timer = '{:02d}:{:02d}'.format(mins, secs)
        print(timer, end="\r")
        time.sleep(1)
        t -= 1
print("Timer completed!")
t = input("Enter the time in seconds")
contdown(int(t))