# -*- coding: utf-8 -*-
"""Python-project(  Rock, paper, scissors .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10gap3nmmgC_SjbfTNhXoOD2j7EQQOWHQ
"""

import random
def play():
  user= input("'r'for rock, 'p' for paper, 's' for scissors\n")
  computer = random.choice(['r', 'p', 's'])

  if user == computer:
     return 'It\'s a tie'

   # r > s, s > p, p > r
  if is_win(user, computer):
      return 'You Won!'

  return 'You lost'


def is_win(player, opponent):
  if (player == 'r' and opponent == 's') or (player == 's' and opponent == 'p') or (player =='p' and opponent == 'r'):
     return True

  print(play())